#!/bin/bash

#THIS=$(readlink -f $0)
THIS=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)/$(basename -- "$0")")
HERE=$(dirname $THIS)

# --- Helper functions ---------------------------------------------------------
. "${HERE}/bash/functions"

# --- Setup Script -------------------------------------------------------------

clear

TMUX=override

echo -e "\n\e[1m\e[4m\e[32mSourcing .bashrc\e[0m"
. $HERE/.bashrc
echo done

em "Updating and upgrading"
sudo apt update && \
sudo apt upgrade && \
sudo apt autoremove || ffs

em "Installing APT packages"
sudo apt install -y $(<$HERE/apt_packages.txt) || ffs

em "Downloading from Github"
install-github-release sharkdp/bat bat amd64
install-github-release sharkdp/vivid vivid amd64
install-github-release cli/cli gh amd64
echo done

em "Installing Node packages"
NVM_VER="0.37.2"
#touch ~/.bash_profile
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VER}/install.sh | bash
. ~/.nvm/nvm.sh
nvm install node
npm install -g $(<$HERE/npm_packages.txt) || ffs
#npm audit fix

em "Setting up environment"
test -e ~/.tmux/plugins/tpm || \
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
addline "$HOME/.bashrc" ". $HERE/.bashrc"
addline "$HOME/.tmux.conf" "source-file $HERE/.tmux.conf"
addline "$HOME/.vimrc" "source $HERE/.vimrc"
echo done

em "Sourcing .bashrc again"
. $HERE/.bashrc
echo done

#em "Sourcing .tmux.conf"
#tmux source-file $HERE/.tmux.conf

