#!/bin/bash

THIS=$(readlink -f $0)
HERE=$(dirname $THIS)

########################
#   Helper functions   #
########################

# Install package from Github Releases
function install-github-release {
    repo=$1
    cmd=$2
    arch=$3
    if [ -z "$(which $cmd)" ]; then
        format "$cmd not found" yellow
    else
        format "$cmd already installed" blue
        return
    fi
    #dl=$(\
    #  	curl -s https://api.github.com/repos/$repo/releases/latest | grep browser | grep amd64 | head -n 1 | cut -d '"' -f 4
    #)
    format "Installing $cmd from $repo for $arch" blue
    latest=$(curl -s https://api.github.com/repos/$repo/releases/latest | grep browser | grep $arch | cut -d '"' -f 4)
    altarr=($latest)
    if [ ${#altarr[@]} -gt 1 ]; then
        for line in ${altarr[@]}; do
            format "  $(basename ${line})" blue
        done
    fi
    dl=${altarr[0]}  # Use first match
    if [ -z "$dl" ]; then
        format "Unable to find release for $repo" red
        return 1
    else
        format "Using: $dl"
    fi
    file=$(basename $dl)
    [ -f "$file" ] && format "$file already downloaded" blue || format "Downloading $file" yellow
    wget $dl
    sudo dpkg -i $file
    rm $file
}

# Add line to file if not already present
function addline () {
    # Add line to file only if it does not already exist
    FILE=$1
    LINE=${@:2}
    touch $FILE
    grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
}


####################
#   Setup Script   #
####################

clear

TMUX=override

echo -e "\n\e[1m\e[4m\e[32mSourcing .bashrc\e[0m"
. $HERE/.bashrc
echo done

em "Updating and upgrading"
sudo apt update && \
sudo apt upgrade

em "Installing APT packages"
sudo apt install -y $(<$HERE/apt_packages.txt | grep -v "#")

em "Downloading from Github"
install-github-release sharkdp/bat bat amd64
install-github-release sharkdp/vivid vivid amd64

em "Setting up environment"
addline "$HOME/.bashrc" ". $HERE/.bashrc"
addline "$HOME/.tmux.conf" "source-file $HERE/.tmux.conf"
addline "$HOME/.vimrc" "source $HERE/.vimrc"
echo done

em "Sourcing .bashrc again"
. $HERE/.bashrc

em "Sourcing .tmux.conf"
tmux source-file $HERE/.tmux.conf

