#!/bin/bash

EDITOR=${EDITOR:-vim}
BROWSER=${BROWSER:-surf}

alias lc="ls -la --color=yes | less -R"
alias lg="git log --all --graph --decorate --color --graph --oneline"
#alias st="git status -uno ." # Replaces suckless terminal
alias cat="bat"
alias src=". ~/.bashrc || true"
#alias lrc="open ~/.bashrc"
alias cd..="cd .."
alias make="colormake"
alias path='echo $PATH | tr ":" "\n"'
alias quick="make -j"
alias tmux-take="tmux a -d -t"
alias pip38="python3.8 -m pip"
alias python38="python3.8"
alias i3-config="$EDITOR ~/.config/i3/config"
alias i3-refcard="$BROWSER https://i3wm.org/docs/refcard.html"

# Direct git upload
function gup () {
  git diff
  git add .
  st  # Only versioned files
  read -r -p "Upload these changes? [y/N] " response
  if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
  then
    printf "Commit message: "
    read commit_message
    git commit -a -m "$commit_message"
    git push
  else
    echo "Cancelled"
  fi
}
