#!/bin/bash

alias gdi="git diff"
alias gst="git status"
alias gfe="git fetch"
alias glo="git log --all --decorate --oneline --graph --color"
alias gpr="git stash && git pull --rebase && git stash pop && echo done"
alias gcm="git commit -m"
